# Gems
gems:
  - jekyll-paginate
plugins: 
  - jekyll-paginate
# Site settings
title: Highlights from books and articles | Melanie Richards
email: brian
url: ""
images: /assets/images/content

# Blog settings
paginate: 10
paginate_path: "/all/page:num/"
permalink: /book/:title/

# Build settings
markdown: kramdown
sass:
  sass_dir: assets/_sass
  style: compressed
